import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/context/AuthProvider";
import Navbar from "../components/ui/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { GroupProvider } from "@/lib/context/GroupContext";
import { TaskProvider } from "@/lib/context/TaskContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <GroupProvider>
        <TaskProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Navbar />
              {children}
              <Toaster />
            </body>
          </html>
        </TaskProvider>
      </GroupProvider>
    </AuthProvider>
  );
}
